### ISSUE TITLE
isMemberOfClass

### ISSUE THREAD

**Issue by leftw** [RuiAAPeres/UIViewController-Swizzled#6]
Hello！
In UIViewController+Swizzled.m
- (void)printPath
  {
  if ([self parentViewController] == nil)
  {
      [self logWithLevel:0];
  }
  else if([[self parentViewController] isMemberOfClass:[UINavigationController class]])
  {
      UINavigationController *nav = (UINavigationController *)[self parentViewController];
      NSInteger integer = [[nav viewControllers] indexOfObject:self];
      [self logWithLevel:integer];
  }
  else if ([[self parentViewController] isMemberOfClass:[UITabBarController class]])
  {
      [self logWithLevel:1];
  }
  }

I think "isMemberOfClass" need to change "isKindOfClass"

isKindOfClass
Returns a Boolean value that indicates whether the receiver is an instance of given class or an instance of any class that inherits from that class. (required)

isMemberOfClass
Returns a Boolean value that indicates whether the receiver is an instance of a given class

**Comment by RuiAAPeres** [comment]
@leftw1222 nice call!
