### ISSUE TITLE
hello,I made a impove for `printPath` method

### ISSUE THREAD

**Issue by TANGBL93** [RuiAAPeres/UIViewController-Swizzled#7]
thanks your good repo,it's very great good and helps me a lot.
but i found that the  `printPath` method may be not unreasonable(不合理)
so i change this method body to :
```
    NSUInteger level = 0;
	UIViewController *parent = [self parentViewController];
	while (parent != nil) {
		level += 1;
		parent = [parent parentViewController];
	}
	[self logWithLevel:level];
```

it depends on whether the current vc has a  parent.i don't know if this is more reasonable(合理).thank you

**Comment by RuiAAPeres** [comment]
Could you send a PR?

**Comment by clangdiagnostic** [comment]
a pr is send,thanks




------------------ 原始邮件 ------------------
发件人: "Rui Peres";<notifications@github.com>;
发送时间: 2015年12月13日(星期天) 上午8:02
收件人: "RuiAAPeres/UIViewController-Swizzled"<UIViewController-Swizzled@noreply.github.com>; 
抄送: "clangdiagnostic"<lollypo@foxmail.com>; 
主题: Re: [UIViewController-Swizzled] hello,I made a impove for `printPath`method (#7)




Could you send a PR?
